# Generated by Django 5.0 on 2023-12-07 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_formulaire_delete_message_delete_person'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Formulaire',
        ),
    ]
