# Generated by Django 4.2 on 2023-12-07 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0005_delete_formulaire'),
    ]

    operations = [
        migrations.CreateModel(
            name='game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.CharField(default='defaultplayer', max_length=100)),
                ('score_game', models.IntegerField()),
            ],
        ),
    ]
